
server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /chat {
        proxy_pass http://lilly_backend:3000/chat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /models {
        proxy_pass http://lilly_backend:3000/models;
    }

    location /stt {
        proxy_pass http://lilly_backend:3000/stt;
    }

    location /tts {
        proxy_pass http://lilly_backend:3000/tts;
    }
}
